FROM satyadeep/BASE_IMAGE
LABEL MAINTAINER="SATYADEEP G" \
      "GitHub Link"="https://github.com/satyadeep" \
      "Drush Version"="DRUSH_FULL_VERSION"

# Set the Drush version.
ENV DRUSH_VERSION DRUSH_FULL_VERSION

# Install Drush using Composer.
RUN composer global require drush/drush:"$DRUSH_VERSION" --prefer-dist

# Display which version of Drush was installed.
RUN /tmp/vendor/bin/drush --version
